Parameters:
  APIGatewayID:
    Description: URL for api gateway
    Type: String

Resources:
  WebAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::Region}"
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: CloudFront-Access
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  WebAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebAppBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Principal:
              Service: "cloudfront.amazonaws.com"
            Effect: Allow
            Resource: !Sub "arn:${AWS::Partition}:s3:::${WebAppBucket}/*"
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins: 
          - DomainName: !GetAtt WebAppBucket.RegionalDomainName
            Id: WebAppBuckPointer
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
            S3OriginConfig:
              OriginAccessIdentity: ""
          - DomainName: !Sub "${APIGatewayID}.execute-api.${AWS::Region}.amazonaws.com"
            Id: APIGateway
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        CacheBehaviors:
          - PathPattern: "/api/*"
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            TargetOriginId: APIGateway
            ViewerProtocolPolicy: "allow-all"
            AllowedMethods: [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
            Compress: false
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac 
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: WebAppBuckPointer
          ViewerProtocolPolicy: allow-all
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        Enabled: true
Outputs:
  CloudFrontID:
    Value: !GetAtt CloudFrontDistribution.Id
  CloudFrontURL:
    Value: !GetAtt CloudFrontDistribution.DomainName
  WebAppBucket:
    Value: !Ref WebAppBucket
